#requires -Version 7.0
[CmdletBinding()]
param([switch]$StableRelease)
$ErrorActionPreference = 'Stop'
# One release timestamp is shared by both UI builds and the native package.
$instant = [DateTimeOffset]::UtcNow
$stamp = $instant.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", [Globalization.CultureInfo]::InvariantCulture)
$utc8 = $instant.ToOffset([TimeSpan]::FromHours(8)).ToString("yyyy-MM-dd'T'HH:mm:sszzz", [Globalization.CultureInfo]::InvariantCulture)
$project = [xml](Get-Content -LiteralPath (Join-Path $PSScriptRoot 'src/ProcessKeeper.App/ProcessKeeper.App.csproj') -Raw)
$version = [string]$project.Project.PropertyGroup.Version
if (-not $version) { throw 'Missing release version.' }
$channel = if ($StableRelease) { 'Stable' } else { 'Preview' }
$source = @"
// Generated by write-build-info.ps1 at the start of the release build. Do not use file timestamps.
using System.Globalization;

namespace ProcessKeeper.Core;

public static class BuildInfo
{
    // Configuration=Release remains Preview unless the stable MSBuild property was explicitly supplied.
#if PROCESSKEEPER_STABLE_RELEASE
    public const string ReleaseChannel = "Stable";
    public static bool IsPreviewBuild => false;
    public const string BuildChannelMarker = "ProcessKeeper.Build.Channel:Stable";
#else
    public const string ReleaseChannel = "Preview";
    public static bool IsPreviewBuild => true;
    public const string BuildChannelMarker = "ProcessKeeper.Build.Channel:Preview";
#endif
    public const string BuildDateUtc = "$stamp";
    public const string BuildDateUtc8 = "$utc8";
    public static string DisplayBuildDate
    {
        get
        {
            // Windows can change its time zone while this app remains open.
            try { TimeZoneInfo.ClearCachedData(); return FormatBuildDate(TimeZoneInfo.Local); }
            catch { return FormatBuildDate(null); }
        }
    }
    public static string FormatBuildDate(TimeZoneInfo? timeZone)
    {
        var instant = DateTimeOffset.ParseExact(BuildDateUtc, "yyyy-MM-dd'T'HH:mm:ss'Z'",
            CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal);
        var shown = timeZone is null ? instant.ToOffset(TimeSpan.FromHours(8)) : TimeZoneInfo.ConvertTime(instant, timeZone);
        return shown.ToString("yyyy-MM-dd HH:mm:ss zzz", CultureInfo.InvariantCulture);
    }
}
"@
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'src/ProcessKeeper.Core/BuildInfo.cs'), $source, [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'build-info.json'), ([ordered]@{ Version=$version; ReleaseChannel=$channel; BuiltAtUtc=$stamp; BuiltAtUtc8=$utc8 } | ConvertTo-Json), [Text.UTF8Encoding]::new($false))
Write-Host "Build channel: $channel | timestamp: $stamp"
