<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
  <OutputType>WinExe</OutputType><TargetFramework>net462</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms>
  <LangVersion>latest</LangVersion><Nullable>enable</Nullable><ImplicitUsings>disable</ImplicitUsings><PlatformTarget>AnyCPU</PlatformTarget><Prefer32Bit>false</Prefer32Bit>
  <AssemblyName>ProcessKeeper</AssemblyName><RootNamespace>ProcessKeeper.App</RootNamespace><Product>Process Keeper</Product><Version>1.6.0</Version><ApplicationManifest>app.manifest</ApplicationManifest>
  <ApplicationIcon>../ProcessKeeper.App/Assets/ProcessKeeper.ico</ApplicationIcon><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
 </PropertyGroup>
 <ItemGroup><Reference Include="System.Net.Http"/>
  <PackageReference Include="WPF-UI" Version="4.3.0"/>
  <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net462" Version="1.0.3" PrivateAssets="all"/>
  <PackageReference Include="System.Text.Json" Version="8.0.6"/>
  <ProjectReference Include="../ProcessKeeper.Legacy.Core/ProcessKeeper.Legacy.Core.csproj"/>
  <Resource Include="../ProcessKeeper.App/Assets/ProcessKeeper.png" Link="Assets/ProcessKeeper.png"/>
 </ItemGroup>
</Project>
