// Generated by write-build-info.ps1 at the start of the release build. Do not use file timestamps.
using System.Globalization;

namespace ProcessKeeper.Core;

public static class BuildInfo
{
    // Configuration=Release remains Preview unless the stable MSBuild property was explicitly supplied.
#if PROCESSKEEPER_STABLE_RELEASE
    public const string ReleaseChannel = "Stable";
    public static bool IsPreviewBuild => false;
    public const string BuildChannelMarker = "ProcessKeeper.Build.Channel:Stable";
#else
    public const string ReleaseChannel = "Preview";
    public static bool IsPreviewBuild => true;
    public const string BuildChannelMarker = "ProcessKeeper.Build.Channel:Preview";
#endif
    public const string BuildDateUtc = "2026-10-07T14:02:07Z";
    public const string BuildDateUtc8 = "2026-10-07T22:02:07+08:00";
    public static string DisplayBuildDate
    {
        get
        {
            // Windows can change its time zone while this app remains open.
            try { TimeZoneInfo.ClearCachedData(); return FormatBuildDate(TimeZoneInfo.Local); }
            catch { return FormatBuildDate(null); }
        }
    }
    public static string FormatBuildDate(TimeZoneInfo? timeZone)
    {
        var instant = DateTimeOffset.ParseExact(BuildDateUtc, "yyyy-MM-dd'T'HH:mm:ss'Z'",
            CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal);
        var shown = timeZone is null ? instant.ToOffset(TimeSpan.FromHours(8)) : TimeZoneInfo.ConvertTime(instant, timeZone);
        return TimeDisplay.Format(shown);
    }
}